### ISSUE TITLE
Windows 10 x86, not compile (eclipse)

### ISSUE THREAD

**Issue by grafdracla** [JavaProphet/Osmium#3]
Hi.
How to compile the client in Windows 10 x86? I tried to run the project in Eclipse, but it gives an error:
`Error starting process.
Cannot run program "C:\Users\nik\Downloads\MinecraftClone-master (4)\MinecraftClone-master\MinecraftClone\Debug\MinecraftClone": Launching failed
Cannot run program "C:\Users\nik\Downloads\MinecraftClone-master (4)\MinecraftClone-master\MinecraftClone\Debug\MinecraftClone": Launching failed
Cannot run program "C:\Users\nik\Downloads\MinecraftClone-master (4)\MinecraftClone-master\MinecraftClone\Debug\MinecraftClone": Launching failed`

Debug:
`Error in final launch sequence
Failed to execute MI command:
-file-exec-and-symbols "C:/Users/nik/Downloads/MinecraftClone-master (4)/MinecraftClone-master/MinecraftClone/Debug/MinecraftClone"
Error message from debugger back end:
"C:/Users/nik/Downloads/MinecraftClone-master (4)/MinecraftClone-master/MinecraftClone/Debug/MinecraftClone": not in executable format: File format not recognized
"C:/Users/nik/Downloads/MinecraftClone-master (4)/MinecraftClone-master/MinecraftClone/Debug/MinecraftClone": not in executable format: File format not recognized`

Sorry, I'm a noob in this case ...
Thank you in advance for your help!

**Comment by Protryon** [comment]
I don't have a clue how to compile on windows for windows, but perhaps some combination of cygwin and mingw will allow it. If you were compiling on Linux for Windows, you would run make all in the DebugWindows folder. You will need to use GCC.

**Comment by grafdracla** [comment]
I apologize for the fact that for a long time did not answer...

I used Eclipse and mingw on Windows, but it does not work.
On Linux is compiled without problems, I'm using the latest version of the compiler GCC 5.3 on ArchLinux.

Thank you for your help and interesting development of Minecraft client.
