### ISSUE TITLE
White screen after minor reconfigurations

### ISSUE THREAD

**Issue by dragos240** [JavaProphet/Osmium#4]
Hi there,

I've been trying to get Osmium to work and after changing models.h so that the "struct model" definition was above the other struct model declarations (because it wouldn't compile until I did that), changing the "INSTALLDIR" from "/dsk/oglt" (or something like that to /home/osaka/.minecraft/ because in the source files it looks like it's looking for the minecraft root directory), and changing -l:libglfw.a to -lglfw (because the linker didn't work like that) the program compiles and runs. Unfortunately this leaves me with a white screen upon running. I compiled the program from the Osmium/Osmium/DebugLinux directory. I'm running on Arch Linux x86_64. A screenshot is attached.
![desktop](https://cloud.githubusercontent.com/assets/704081/15431445/ee86c3d0-1e77-11e6-8aa5-e9624cdda7e8.png)

**Comment by Protryon** [comment]
It probably failed to find assets, this is NOT supposed to run in .minecraft. It is designed to run in it's own directory with an assets folder extracted from 1.9.x Minecraft Jar. I will be more explicit and write installation instructions. Thank you for reporting. Let me know if the issue continues (It might be your OGL version/drivers possibly, I've not done extensive compatibility testing)

EDIT: The glfw I made static because (specifically Ubuntu/LM) don't have glfw3 available. If you can combine it through dl, all the better, but this is untested from my end.

**Comment by dragos240** [comment]
Okay so after taking your advice, it works!.... mostly. On the title screen there are random pixels that jump about (See screenshot). And after logging on to my local server, it works fine (no pixels everywhere)... until it segfaults. It appeared to crash my Xorg session as well. I had to tab out to tty1 and back to tty7 (where xorg is running) to get it to unfreeze.
![desktop](https://cloud.githubusercontent.com/assets/704081/15432577/cec27af8-1e7c-11e6-97d8-6e2818113fe6.png)

**Comment by Protryon** [comment]
This is a known bug that I have too. Despite it being bad to look at, I haven't had the time and priority to fix it. Can you run it under Valgrind and send me the output? If you use FGLRX, make sure to use the valgrind-supp file in the DebugLinux directory.
IE, valgrind --suppressions=./valgrind-supp ./Osmium
And I will go about solving that segfault.

**Comment by dragos240** [comment]
I do indeed use fglrx. I'm attaching the result of valgrind --suppressions=./valgrind-supp ./Osmium > errors.txt 2>&1. I ran it for a few minutes and it surprisingly did not crash (although it was very laggy, but this could be the fault of valgrind).
[errors.txt](https://github.com/JavaProphet/Osmium/files/274926/errors.txt)

**Comment by Protryon** [comment]
Yes, valgrind does slow it down a lot. It seems as if there is nothing but a huge memory leak. 
I pushed an update, I'm going to continue testing when I get home.

**Comment by Protryon** [comment]
I've fixed the memory leaks and segfault.
