### ISSUE TITLE
White screen... (still)

### ISSUE THREAD

**Issue by marcdraco** [JavaProphet/Osmium#6]
I've copied the Osmium executable to its own folder and move the assets folder (complete) into that but I'm still getting a white screen. Terminal output is:

Loading... [FROM=./]
OpenGL Version: 3.0 Mesa 11.2.0
Loaded.
FPS: 62.083672
FPS: 60.018055
FPS: 59.940464
FPS: 60.025924
FPS: 59.977064

(etc.)

Probably my smeg up but I don't know how to see what (if anything) the program is trying to load! :/

**Comment by Protryon** [comment]
Is your assets folder from inside a 1.9.x jar? (not from the .minecraft/assets)?

**Comment by marcdraco** [comment]
That would be mea culpa then. I must be missing something because when I examine the minecraft.jar from Mojang (appx. 280.2Kb) it only appears to contain Java .class files.

If would be kind enough to guide me to where I might find the correct file I'll happily write up some more "by the hand" instructions for the blind (like me). ;)

**Comment by Protryon** [comment]
I have a feeling your looking in the launcher. Look in .minecraft/versions/1.9.x/1.9.x.jar.

**Comment by marcdraco** [comment]
Well slap me silly with the slimy end of a wet trout! I That fixed the "startup" assets (thank you) - console output below. 

To save opening a new issue, I am unable to connect to my local server (says "failed to log in") 
and the other options are grayed out (see screengrab). 

Quite excited for this dear chap - my poor laptop sounds like a 747 at full throttle running the Java and barely opens an eye when running yours... (Much the same happens on the server: I'm running Cuberite on ARM development board - OrangePI PC.) Such is the inefficiency of Java. :(

Of course, Cuberite might be the issue so would appreciate your advice. I also have Spigot which is pure Java although the load on the server is, as you might imagine, untenable.

So I'm happy to be a bit of crash-test dummy. Minecraft has been lacking an efficient client until you achieved this!

![mc](https://cloud.githubusercontent.com/assets/8806862/15634420/07f48ff6-25bb-11e6-824d-4b1e4208fccf.png)

Loading... [FROM=./]
OpenGL Version: 3.0 Mesa 11.2.0
Warning: model <cobblestone_wall_ns> has an invalid parent!
Warning: model <cobblestone_wall_nsew> has an invalid parent!
Warning: model <cobblestone_wall_ns_above> has an invalid parent!
Warning: model <cobblestone_wall_ne> has an invalid parent!
Warning: model <cobblestone_wall_nse> has an invalid parent!
Loaded.
FPS: 61.847861

**Comment by Protryon** [comment]
It doesn't support online mode yet, and is strictly MC 1.9.4 (no protocol hacks). I pushed a render fix for the multiplayer menu too. Let me know if those buttons remain blurred/funky.

**Comment by marcdraco** [comment]
Ah, my bad over multiplayer. I don't have access to anything other that these screens right now - but I can see the "burred landscape" behind is rotating as it should. 

Should I have generated a landscape in single player first, perhaps? I'm really doing this for my kids - but I'm happy to help testing the releases. I'm on Ubuntu Mate 16.04 and compiled the GL drivers (?!) from source since it did come with the distro. Thankfully your compilation instructions made that bit clear. :)

![mc](https://cloud.githubusercontent.com/assets/8806862/15634573/4c7e45e6-25bf-11e6-9d98-34bfce367811.png)

**Comment by Protryon** [comment]
It seems as if your drivers are forcing antialiasing/GL_NEAREST mode. As I'm sure you've noticed, text and buttons have issues because of that. Also, this isn't quite play-ready yet, you cannot interact with the world(break/place/open chests/attack/etc).

**Comment by marcdraco** [comment]
Ah - with you - well if you need me to run any tests, you only have to ask: I guess if we keep this "issue" open that's the easiest way for me. You might have noticed I'm rather new to Git (except being an "old git" - positively prehistoric in real terms as I descend from 4 [yes four]-bit microcontroller days). The 6502, Z80, 8008 and others were state of the art then! :)

**Comment by louwers** [comment]
Text looks beautiful now.

Water is very trippy.

![screenshot_2016-06-04_20-37-05](https://cloud.githubusercontent.com/assets/649392/15801416/29d59326-2a94-11e6-9018-3ff7fc39a28a.png)

**Comment by Protryon** [comment]
@louwers Water isn't implemented yet, but I'm working on a change to modelling that will implement all blocks.
